# Generated by Django 4.1.2 on 2022-11-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='que',
            name='email',
        ),
        migrations.AddField(
            model_name='que',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
